current_weather.settings:
  type: config_object
  label: Settings of the current_weather module
  mapping:
    default_city_name:
      type: string
      label: 'Default configuration for city name'
    default_country_code:
      type: string
      label: 'Default configuration for country code'
    api_key:
      type: string
      label: 'API key'
    api_endpoint:
      type: string
      label: 'API endpoint'
